### ISSUE TITLE
Rounding Error using time-varying ratchets

### ISSUE THREAD

**Issue by carlobindaeq** [cmdty/storage#30] opened 2023-06-21 07:41 UTC
Hi,

we've implemented your model in a context where is necessary to have time varying ratchets across the simulation period, in order to reach target filling levels on specific dates.

Depending on the starting inventory level and the ratchets for that time frame, we are incurring into this strange error which seems to be related to some non-well managed rounding operations behind the scenes:

`    self.results: MultiFactorValuationResults = three_factor_seasonal_value(
  File "/azureml-envs/azureml_56ff17e21e8cba7e88bd7ac0a5656619/lib/python3.10/site-packages/cmdty_storage/multi_factor.py", line 361, in three_factor_seasonal_value
    return _net_multi_factor_calc(cmdty_storage, fwd_curve, interest_rates, inventory, add_multi_factor_sim,
  File "/azureml-envs/azureml_56ff17e21e8cba7e88bd7ac0a5656619/lib/python3.10/site-packages/cmdty_storage/multi_factor.py", line 460, in _net_multi_factor_calc
    intrinsic_result = cs_intrinsic.net_intrinsic_calc(cmdty_storage, net_current_period, net_interest_rate_time_series,
  File "/azureml-envs/azureml_56ff17e21e8cba7e88bd7ac0a5656619/lib/python3.10/site-packages/cmdty_storage/intrinsic.py", line 82, in net_intrinsic_calc
    net_val_results = net_cs.IIntrinsicCalculate[time_period_type](intrinsic_calc).Calculate()
System.ArgumentException: Inventory of 6872.954213832093 is below minimum allowed value of 6873 during period 2021-11-01. (Parameter 'inventory')
   at Cmdty.Storage.CmdtyStorage`1.GetInjectWithdrawRange(T date, Double inventory) in C:\Users\Jake\source\repos\storage\src\Cmdty.Storage\StorageEntity\CmdtyStorage.cs:line 94
   at Cmdty.Storage.StorageHelper.CalculateInventorySpace[T](ICmdtyStorage`1 storage, Double startingInventory, T currentPeriod) in C:\Users\Jake\source\repos\storage\src\Cmdty.Storage\StorageHelper.cs:line 42
   at Cmdty.Storage.IntrinsicStorageValuation`1.Calculate(T currentPeriod, Double startingInventory, TimeSeries`2 forwardCurve, ICmdtyStorage`1 storage, Func`2 settleDateRule, Func`3 discountFactors, Func`2 gridCalcFactory, IInterpolatorFactory interpolatorFactory, Double numericalTolerance) in C:\Users\Jake\source\repos\storage\src\Cmdty.Storage\IntrinsicValuation\IntrinsicStorageValuation.cs:line 154
   at Cmdty.Storage.IntrinsicStorageValuation`1.Cmdty.Storage.IIntrinsicCalculate<T>.Calculate() in C:\Users\Jake\source\repos\storage\src\Cmdty.Storage\IntrinsicValuation\IntrinsicStorageValuation.cs:line 116
`
We tried to use RatchetInterp.STEP, but this is apparently failing whenever ratchets are time-varying.

Any idea to prevent this error?

**Comment by cmdty** [comment] 2023-06-21 08:04
Hi @carlobindaeq ideally I need to see the code which creates the storage object and runs the valuation to debug the code and understand this. If you don’t want to post this on GitHub you can email it. At a minimum I need to see the code which creates the storage object, the current inventory and the valuation date.

**Comment by carlobindaeq** [comment] 2023-06-21 08:17
Hi,

I can share the code but is a really complex Python script running on Azure Machine Learning with a lot of input data dependencies.

I can try replicate the error into a simplified Notebook to share but it will take some time. I just wanted to know if you already experienced this and how did you solved the issue.

Thanks,
Carlo
________________________________

**Comment by cmdty** [comment] 2023-06-21 08:45
Which version of the Python package are you using?

**Comment by carlobindaeq** [comment] 2023-06-21 08:48
Python version is 3.10.9.

Thanks,
Carlo
________________________________

**Comment by cmdty** [comment] 2023-06-21 08:58
And the version of the cmdty-storage package?

**Comment by carlobindaeq** [comment] 2023-06-21 09:02
1.3.0
________________________________

**Comment by cmdty** [comment] 2023-06-21 10:10
Thanks, that’s the latest version. Just wanted to check that you weren’t using an older version which had bugs that have been fixed.

Given the information so far I’m not sure what the problem is. However, the valuation with step ratchets is generally quite fickle with regards to the inputs. One quick fix you could try is changing the numerical_tolerance parameter to the valuation function, making it larger than its default value of 1E-12. Have a go, but if this value is too large it can cause other problems. See if it works and if so let me know which value is used.

**Comment by carlobindaeq** [comment] 2023-06-21 10:54
I got this error even running with numerical_tolerance = 1.

Right now I'm doing another simulation using:

  *   numerical_tolerance = 10
  *   using STEP interpolation

I've noticed that STEP is pretty fickle to inputs, indeed I was getting this error on ratchets "ArgumentException: Top two ratchets do not have he same max injection rate. (Parameter 'injectWithdrawRanges')" even if I was using just one ratchet across the entire simulation period.

The ratchet originally was:

ratchet = [(0.0, -48.6, 31.0),
 (1472.7, -97.2, 31.0),
 (2159.96, -108.0, 29.45),
 (9818.0, -108.0, 21.7)]

Apparently (not sure why), changing the ratchet by duplicating the last element seems to solve the problem:

ratchet_mod = [(0.0, -48.6, 31.0),
 (1472.7, -97.2, 31.0),
 (2159.96, -108.0, 29.45),
 (9818.0, -108.0, 21.7),
 (9818.0, -108.0, 21.7)]

I'm going for STEP interpolation with rounded (no decimal values) ratchets values because it looked like the issue was caused by some rounding erros generated by injection/withdrawal numbers with decimal places (e.g. 12.348975). I hope that this workaround can prevent us by hitting this error.

If that doesn't work neither, I will put a simple try/catch statement where the second run of the three_factor_seasonal_value() model is performed without time-varying ratchets.

________________________________

**Comment by cmdty** [comment] 2023-06-21 12:38
For step ratchets the last 2 ratchet tuples need to have the same injection and withdrawal rates, but unlike the example you put above, I would expect that the inventory (the 1st item in each tuple) would be different for the last 2 ratchets. This is due to the definition of step ratchets, i.e. that over a certain ranges of inventories, the injection and withdrawal rates remain constant.

Also, numerical tolerance of 10 and 1 looks way to big for these examples. If this is fixing the valuation then clearly something fishy is going on as it should work with a tolerance of much less than 1 for these ratchets.

**Comment by cmdty** [comment] 2023-11-01 09:46
@carlobindaeq would it be possible to share a self-contained example of the problem that I can debug? I don't particularly like fix you propose above with try/catch. If you can't provide something which can be debugged I'll close this issue for now. Another GitHub issue can be opened once the debuggable example is available.

**Closed** 2023-11-01 21:33 UTC
